- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
- name: Copy nginx config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
- name: Copy custom sites config file
  template:
    src: "sites/{{ group_names[0] }}.j2"
    dest: /etc/nginx/sites-enabled/site.conf
- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: service_default_state | default('started') == 'started'