- name: Modify ulimit setting
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
  - { domain: 'root', limit_type: '-', limit_item: 'nofile', value: '655350' }
  - { domain: '*', limit_type: '-', limit_item: 'nofile', value: '655350' }