# tasks file for fail2ban
---
- name: install
  apt:
    name: "{{ fail2banVersion | default('fail2ban') }}"
    state: "present"
    update_cache: true
    # cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - fail2ban
    - fail2ban-install

- name: update configuration file - /etc/fail2ban/jail.local
  template:
    src: etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-configuration